<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\AudioConverter.Core\AudioConverter.Core.csproj" />
    <ProjectReference Include="..\AudioConverter.Infrastructure\AudioConverter.Infrastructure.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>CodecTone.Cli</AssemblyName>
    <RootNamespace>AudioConverter.Cli</RootNamespace>
    <Version>1.1.0</Version>
  </PropertyGroup>
</Project>
