<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AudioConverter.Core\AudioConverter.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\remix-hall-ir.wav" LogicalName="AudioConverter.Infrastructure.Assets.remix-hall-ir.wav" />
  </ItemGroup>

</Project>
